"""Recovery tests use private homes under the repository; no desktop is touched."""

import importlib.util
import io
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch


ROOT = Path(__file__).resolve().parents[1]
USR = ROOT / 'files/system/usr'
SPEC = importlib.util.spec_from_file_location('configuration', USR / 'libexec/hypratomic/config.py')
MODULE = importlib.util.module_from_spec(SPEC)
# Tests must not leave generated bytecode in the image payload.
with patch.object(sys, 'dont_write_bytecode', True):
    SPEC.loader.exec_module(MODULE)


class ConfigurationTests(unittest.TestCase):
    def setUp(self):
        cache = ROOT / '.cache/tests'
        cache.mkdir(parents=True, exist_ok=True)
        self.temporary = tempfile.TemporaryDirectory(dir=cache)
        self.addCleanup(self.temporary.cleanup)
        self.home = Path(self.temporary.name)
        self.config = MODULE.Configuration(self.home, self.home / '.config',
                                           self.home / '.local/state', USR)
        # These tests exercise transactions, not a substitute Hyprland parser.
        self.preflight = patch.object(self.config, 'preflight').start()
        self.verify = patch.object(self.config, 'verify').start()
        self.addCleanup(patch.stopall)
        patch('sys.stdout', new_callable=io.StringIO).start()

    def original(self):
        self.config.active.mkdir(parents=True)
        (self.config.active / 'hyprland.conf').write_text('known good conf\n')
        (self.config.active / 'hyprland.lua').write_text('-- known good lua\n')
        (self.config.active / 'nested').mkdir()
        (self.config.active / 'nested/monitors.conf').write_text('machine-specific\n')

    def test_directory_round_trip_and_outgoing_archive(self):
        self.original()
        self.config.run('activate')
        self.assertFalse((self.config.active / 'hyprland.lua').exists())
        record = self.config.read_record()
        (self.config.active / 'personal-note').write_text('keep this')
        self.config.run('restore')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')
        self.assertEqual((self.config.active / 'hyprland.lua').read_text(), '-- known good lua\n')
        self.assertEqual((self.config.active / 'nested/monitors.conf').read_text(), 'machine-specific\n')
        self.assertFalse(self.config.record.exists())
        notes = list((self.config.state / 'backups').glob('*/displaced/personal-note'))
        self.assertEqual(len(notes), 1)
        self.assertTrue((Path(record['backup']) / 'original/hyprland.conf').exists())

    def test_absent_original_restores_absence(self):
        self.config.run('activate')
        self.config.run('restore')
        self.assertFalse(MODULE.exists(self.config.active))

    def test_relative_directory_symlink_round_trip_and_snapshot(self):
        target = self.home / '.config/wayblue'
        target.mkdir(parents=True)
        (target / 'hyprland.conf').write_text('external original')
        self.config.active.symlink_to('wayblue')
        self.config.run('activate')
        record = self.config.read_record()
        snapshot = Path(record['backup']) / 'original-contents/hyprland.conf'
        self.assertEqual(snapshot.read_text(), 'external original')
        self.assertEqual((target / 'hyprland.conf').read_text(), 'external original')
        self.config.run('restore')
        self.assertTrue(self.config.active.is_symlink())
        self.assertEqual(os.readlink(self.config.active), 'wayblue')

    def test_file_symlinks_inside_original_are_preserved(self):
        self.original()
        (self.config.active / 'monitor-link').symlink_to('nested/monitors.conf')
        self.config.run('activate')
        self.config.run('restore')
        self.assertEqual(os.readlink(self.config.active / 'monitor-link'), 'nested/monitors.conf')

    def test_repeated_activation_preserves_recovery_point(self):
        self.original()
        self.config.run('activate')
        record = self.config.record.read_bytes()
        self.config.run('activate')
        self.assertEqual(self.config.record.read_bytes(), record)
        self.verify.assert_called_once()

    def test_repeated_restore_is_harmless(self):
        self.original()
        self.config.run('activate')
        self.config.run('restore')
        self.config.run('restore')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')

    def test_bootstrap_preserves_user_files_and_old_staging(self):
        self.config.run('bootstrap')
        override = self.config.user / 'user.conf'
        override.write_text('# personal override\n')
        (self.config.user / 'hypr').mkdir()
        (self.config.user / 'hypr/README.md').write_text('Phase 1 staging')
        self.config.run('bootstrap')
        self.config.run('activate')
        self.config.run('restore')
        self.assertEqual(override.read_text(), '# personal override\n')
        self.assertEqual((self.config.user / 'hypr/README.md').read_text(), 'Phase 1 staging')

    def test_invalid_configuration_does_not_replace_original(self):
        self.original()
        self.verify.side_effect = subprocess.CalledProcessError(1, ['Hyprland'])
        with self.assertRaises(subprocess.CalledProcessError):
            self.config.run('activate')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')
        self.assertFalse(self.config.record.exists())
        self.assertEqual(list(self.config.active.parent.glob('.hypratomic-stage-*')), [])

    def test_dry_run_writes_nothing(self):
        self.config.run('activate', dry_run=True)
        self.assertEqual(list(self.home.iterdir()), [])

    def test_missing_dependencies_do_not_replace_original(self):
        self.original()
        self.preflight.side_effect = RuntimeError('Missing prerequisites')
        with self.assertRaises(RuntimeError):
            self.config.run('activate')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')
        self.assertFalse(self.config.record.exists())

    def test_failed_install_rename_recovers_original(self):
        self.original()
        rename = Path.rename
        def failing_rename(path, target):
            if path.name.startswith('.hypratomic-stage-'):
                raise OSError('simulated install failure')
            return rename(path, target)
        with patch.object(Path, 'rename', failing_rename):
            with self.assertRaises(OSError):
                self.config.run('activate')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')
        self.assertFalse(self.config.pending.exists())
        self.assertFalse(self.config.record.exists())

    def test_failed_commit_recovers_original(self):
        self.original()
        write = MODULE.write_json
        def failing_write(path, value):
            if path == self.config.record:
                raise OSError('simulated state write failure')
            return write(path, value)
        with patch.object(MODULE, 'write_json', failing_write):
            with self.assertRaises(OSError):
                self.config.run('activate')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')
        self.assertFalse(self.config.pending.exists())

    def test_interrupted_activation_recovered_on_next_restore(self):
        self.original()
        # Simulate SIGKILL after both renames but before committing active.json.
        self.config.state.mkdir(parents=True)
        transaction = self.config.transaction()
        displaced = self.config.active.parent / '.hypratomic-previous-test'
        self.config.active.rename(displaced)
        self.config.active.mkdir()
        (self.config.active / 'hyprland.conf').write_text('incomplete new profile')
        MODULE.write_json(self.config.pending, dict(active=str(self.config.active),
                          displaced=str(displaced), transaction=str(transaction),
                          had_original=True, old_record=None))
        self.config.run('restore')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')
        self.assertEqual((transaction / 'interrupted/hyprland.conf').read_text(), 'incomplete new profile')

    def test_failed_restore_keeps_active_configuration_and_recovery_point(self):
        self.original()
        self.config.run('activate')
        record = self.config.record.read_bytes()
        rename = Path.rename
        def failing_rename(path, target):
            if path.name.startswith('.hypratomic-restore-'):
                raise OSError('simulated restore failure')
            return rename(path, target)
        with patch.object(Path, 'rename', failing_rename):
            with self.assertRaises(OSError):
                self.config.run('restore')
        self.assertEqual(self.config.record.read_bytes(), record)
        self.assertTrue((self.config.active / '.hypratomic-profile').exists())
        self.config.run('restore')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')

    def test_missing_backup_refuses_restore(self):
        self.original()
        self.config.run('activate')
        record = self.config.read_record()
        shutil.rmtree(Path(record['backup']) / 'original')
        with self.assertRaisesRegex(RuntimeError, 'Missing backup'):
            self.config.run('restore')
        self.assertTrue((self.config.active / '.hypratomic-profile').exists())

    def test_external_replacement_refuses_reactivation(self):
        self.config.run('activate')
        (self.config.active / '.hypratomic-profile').unlink()
        with self.assertRaisesRegex(RuntimeError, 'replaced'):
            self.config.run('activate')

    def test_broken_symlink_refuses_activation_without_following_it(self):
        self.config.active.parent.mkdir(parents=True)
        self.config.active.symlink_to('missing')
        with self.assertRaises(RuntimeError):
            self.config.run('activate')
        self.assertEqual(os.readlink(self.config.active), 'missing')

    def test_restore_does_not_require_hyprland_or_dependencies(self):
        self.config.run('activate')
        self.preflight.side_effect = RuntimeError('No graphical software')
        self.verify.side_effect = RuntimeError('No compositor')
        self.config.run('restore')
        self.assertFalse(MODULE.exists(self.config.active))

    def test_xdg_overrides_do_not_change_wayblue_entry_point(self):
        self.config.user = self.home / 'custom-config/hypratomic'
        self.config.state = self.home / 'custom-state/hypratomic'
        self.config.record = self.config.state / 'active.json'
        self.config.pending = self.config.state / 'pending.json'
        self.config.run('activate')
        self.assertTrue((self.home / '.config/hypr/hyprland.conf').exists())
        self.assertTrue((self.config.user / 'monitors.conf').exists())
        self.assertIn(str(self.config.user), (self.config.active / 'hyprland.conf').read_text())

    def test_lua_profile_does_not_leave_conf_entry_point(self):
        self.original()
        self.config.format = 'lua'
        self.config.run('activate')
        self.assertTrue((self.config.active / 'hyprland.lua').exists())
        self.assertFalse((self.config.active / 'hyprland.conf').exists())
        self.assertTrue((self.config.user / 'monitors.lua').exists())
        self.config.run('restore')
        self.assertTrue((self.config.active / 'hyprland.conf').exists())

    def test_overlapping_state_is_rejected(self):
        self.config.state = self.config.active / 'state'
        with self.assertRaisesRegex(RuntimeError, 'overlap'):
            self.config.run('activate')

    def test_absolute_directory_symlink_round_trip(self):
        target = self.home / 'wayblue'
        target.mkdir()
        (target / 'hyprland.conf').write_text('absolute target')
        self.config.active.parent.mkdir(parents=True)
        self.config.active.symlink_to(target)
        self.config.run('activate')
        self.config.run('restore')
        self.assertEqual(os.readlink(self.config.active), str(target))
        self.assertEqual((target / 'hyprland.conf').read_text(), 'absolute target')

    def test_interruption_before_first_rename_keeps_original(self):
        self.original()
        self.config.state.mkdir(parents=True)
        transaction = self.config.transaction()
        MODULE.write_json(self.config.pending, dict(active=str(self.config.active),
                          displaced=str(self.config.active.parent / '.hypratomic-previous-test'),
                          transaction=str(transaction), had_original=True, old_record=None))
        self.config.run('restore')
        self.assertEqual((self.config.active / 'hyprland.conf').read_text(), 'known good conf\n')

    def test_interruption_with_no_original_restores_absence(self):
        self.config.state.mkdir(parents=True)
        transaction = self.config.transaction()
        self.config.active.mkdir(parents=True)
        (self.config.active / 'hyprland.conf').write_text('interrupted profile')
        MODULE.write_json(self.config.pending, dict(active=str(self.config.active),
                          displaced=str(self.config.active.parent / '.hypratomic-previous-test'),
                          transaction=str(transaction), had_original=False, old_record=None))
        self.config.run('restore')
        self.assertFalse(self.config.active.exists())
        self.assertEqual((transaction / 'interrupted/hyprland.conf').read_text(), 'interrupted profile')

    def test_refuse_state_reuse_with_different_home(self):
        self.config.run('activate')
        self.config.active = self.home / 'other-user/.config/hypr'
        with self.assertRaisesRegex(RuntimeError, 'different HOME'):
            self.config.run('restore')

    def test_validation_is_parse_only_with_isolated_runtime(self):
        config_file = self.home / 'hyprland.conf'
        config_file.write_text('# test')
        runtimes = []
        def validate(arguments, *, env, check):
            self.assertIn('--verify-config', arguments)
            self.assertIn('--i-am-really-stupid', arguments)
            self.assertTrue(check)
            runtime = Path(env['XDG_RUNTIME_DIR'])
            self.assertEqual(runtime.parent, self.home)
            self.assertEqual(runtime.stat().st_mode & 0o777, 0o700)
            runtimes.append(runtime)
        with patch.object(MODULE.shutil, 'which', return_value='/usr/bin/Hyprland'), \
                patch.object(MODULE.os, 'geteuid', return_value=0), \
                patch.object(MODULE.subprocess, 'run', side_effect=validate):
            MODULE.Configuration.verify(self.config, config_file)
        self.assertEqual(len(runtimes), 1)
        self.assertFalse(runtimes[0].exists())


if __name__ == '__main__':
    unittest.main()
