#!/usr/bin/env python3
"""Per-user configuration transactions. No root, compositor, or service mutation."""

import argparse
import fcntl
import json
import os
from pathlib import Path
import shutil
import signal
import subprocess
import sys
import tempfile
import uuid


def exists(path):
    return path.exists() or path.is_symlink()


def copy_entry(source, target):
    if source.is_symlink():
        target.symlink_to(os.readlink(source))
    elif source.is_dir():
        shutil.copytree(source, target, symlinks=True)
    else:
        shutil.copy2(source, target)


def write_json(path, value):
    temporary = path.with_suffix('.tmp')
    with temporary.open('w') as stream:
        json.dump(value, stream, indent=2)
        stream.flush()
        os.fsync(stream.fileno())
    temporary.replace(path)


class Configuration:
    def __init__(self, home, config_home, state_home, usr):
        self.usr = Path(usr)
        # Wayblue's starthyprland explicitly reads HOME/.config, not XDG_CONFIG_HOME.
        self.active = Path(home) / '.config/hypr'
        self.user = Path(config_home) / 'hypratomic'
        self.state = Path(state_home) / 'hypratomic'
        self.defaults = self.usr / 'share/hypratomic/hypr'
        self.format = 'lua'
        self.record = self.state / 'active.json'
        self.pending = self.state / 'pending.json'

    def check_paths(self):
        for path in (self.active, self.user, self.state, self.defaults):
            if not path.is_absolute() or any(c in str(path) for c in '\n\r#$'):
                raise RuntimeError(f'Unsupported configuration path: {path}')
        for path in (self.user, self.state):
            if path.is_symlink() or (exists(path) and not path.is_dir()):
                raise RuntimeError(f'Expected a real directory: {path}')
        paths = [p.resolve() for p in (self.active, self.user, self.state)]
        for i, left in enumerate(paths):
            for right in paths[i + 1:]:
                if left == right or left in right.parents or right in left.parents:
                    raise RuntimeError('Active configuration, user overrides and state must not overlap')

    def bootstrap(self):
        self.check_paths()
        self.user.mkdir(parents=True, exist_ok=True)
        templates = self.defaults / 'user'
        for source in sorted(templates.iterdir()):
            target = self.user / source.name
            if exists(target):
                if not target.is_file():
                    raise RuntimeError(f'Expected an override file: {target}')
                continue
            with target.open('x') as stream:
                stream.write(source.read_text())
        print(f'User overrides: {self.user} (existing files preserved)')

    def preflight(self):
        commands = ('foot', 'waybar', 'quickshell', 'walker', 'elephant', 'distrobox', 'yazi', 'tmux', 'nvim', 'wl-copy', 'wl-paste',
                    'cliphist', 'grim', 'slurp', 'swayidle', 'swaylock',
                    'dbus-update-activation-environment', 'gnome-keyring-daemon',
                    'nm-applet', 'pgrep', 'flock')
        missing = [name for name in commands if not shutil.which(name)]
        if not (shutil.which('Hyprland') or shutil.which('hyprland')):
            missing.append('Hyprland')
        for relative in ('libexec/xfce-polkit', 'libexec/pam_kwallet_init',
                         'share/swayidle/config'):
            if not (self.usr / relative).is_file():
                missing.append(str(self.usr / relative))
        if missing:
            raise RuntimeError('Missing image prerequisites: ' + ', '.join(missing))

    def loader(self, directory):
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / 'hyprland.lua'
        text = ('-- Generated by hypratomic-activate; edit the user overrides.\n'
                'hypratomic = { defaults = ' + json.dumps(str(self.defaults), ensure_ascii=False) +
                ', user = ' + json.dumps(str(self.user), ensure_ascii=False) + ' }\n'
                'dofile(hypratomic.defaults .. "/hyprland.lua")\n')
        path.write_text(text)
        return path

    def verify(self, path):
        executable = shutil.which('Hyprland') or shutil.which('hyprland')
        if not executable:
            raise RuntimeError('Hyprland is required to validate the configuration')
        arguments = [executable, '--verify-config', '-c', str(path)]
        if os.geteuid() == 0:
            # Image builds run as root. This is parse-only, never a root desktop.
            arguments.append('--i-am-really-stupid')
        # Hyprland requires a runtime directory even for parse-only validation.
        # Keep its validation files isolated from any live compositor session.
        with tempfile.TemporaryDirectory(prefix='.hypratomic-verify-', dir=path.parent) as runtime:
            environment = dict(os.environ, XDG_RUNTIME_DIR=runtime)
            subprocess.run(arguments, env=environment, check=True)

    def transaction(self):
        path = self.state / 'backups' / uuid.uuid4().hex
        path.mkdir(parents=True)
        return path

    def read_record(self):
        if not self.record.exists():
            return None
        record = json.loads(self.record.read_text())
        if (not isinstance(record, dict) or
                not isinstance(record.get('active'), str) or
                not isinstance(record.get('backup'), str) or
                not isinstance(record.get('original'), bool)):
            raise RuntimeError(f'Invalid recovery record: {self.record}; configuration was not touched')
        if record['active'] != str(self.active):
            raise RuntimeError('Recovery state belongs to a different HOME')
        backup = Path(record['backup'])
        if backup.parent != self.state / 'backups' or backup.is_symlink():
            raise RuntimeError(f'Unexpected recovery backup path: {backup}')
        return record

    def recover(self):
        """An interrupted swap is rolled back before accepting another command."""
        if not self.pending.exists():
            return False
        data = json.loads(self.pending.read_text())
        if data['active'] != str(self.active):
            raise RuntimeError('Pending transaction belongs to a different HOME')
        displaced = Path(data['displaced'])
        transaction = Path(data['transaction'])
        if exists(displaced):
            if exists(self.active):
                shutil.move(str(self.active), str(transaction / 'interrupted'))
            displaced.rename(self.active)
        elif not data['had_original'] and exists(self.active):
            shutil.move(str(self.active), str(transaction / 'interrupted'))
        if data['old_record'] is None:
            self.record.unlink(missing_ok=True)
        else:
            write_json(self.record, data['old_record'])
        self.pending.unlink()
        print(f'Recovered interrupted configuration swap; archive: {transaction}')
        return True

    def swap(self, staged, transaction, new_record):
        displaced = self.active.parent / ('.hypratomic-previous-' + transaction.name)
        data = dict(active=str(self.active), displaced=str(displaced),
                    transaction=str(transaction), had_original=exists(self.active),
                    old_record=self.read_record())
        write_json(self.pending, data)
        try:
            if exists(self.active):
                self.active.rename(displaced)
            if staged is not None:
                staged.rename(self.active)
            if new_record is None:
                self.record.unlink(missing_ok=True)
            else:
                write_json(self.record, new_record)
            self.pending.unlink()
        except BaseException:
            self.recover()
            raise
        # The swap is committed. Archiving failure must not undo a working swap.
        if exists(displaced):
            try:
                shutil.move(str(displaced), str(transaction / 'displaced'))
            except OSError as error:
                print(f'Configuration saved at {displaced}; archive failed: {error}', file=sys.stderr)

    def activate(self):
        record = self.read_record()
        if record:
            marker = self.active / '.hypratomic-profile'
            if not marker.is_file() or marker.read_text() != record['backup']:
                raise RuntimeError('Active configuration was replaced; restore before activating again')
            print('Already active; the original recovery point is unchanged')
            return
        self.preflight()
        if exists(self.active) and not self.active.is_dir():
            raise RuntimeError(f'Expected a directory or valid directory symlink: {self.active}')
        transaction = self.transaction()
        if exists(self.active):
            copy_entry(self.active, transaction / 'original')
            if self.active.is_symlink():
                shutil.copytree(self.active, transaction / 'original-contents', symlinks=True)
        self.bootstrap()
        self.active.parent.mkdir(parents=True, exist_ok=True)
        staged = Path(tempfile.mkdtemp(prefix='.hypratomic-stage-', dir=self.active.parent))
        try:
            self.verify(self.loader(staged))
            (staged / '.hypratomic-profile').write_text(str(transaction))
            record = dict(active=str(self.active), backup=str(transaction), format=self.format,
                          original=exists(self.active))
            self.swap(staged, transaction, record)
        finally:
            if staged.exists():
                # Only our new staging directory is removed, never a user configuration.
                shutil.rmtree(staged)
        print(f'Activated {self.format} defaults. Recovery point: {transaction}')
        print('Log out and log in for the complete session change. TTY recovery: hypratomic-restore')

    def restore(self):
        record = self.read_record()
        if record is None:
            print('No active Hypratomic configuration to restore')
            return
        backup = Path(record['backup'])
        source = backup / 'original'
        if record['original'] and not exists(source):
            raise RuntimeError(f'Missing backup: {source}; active configuration was not touched')
        transaction = self.transaction()
        staged = None
        self.active.parent.mkdir(parents=True, exist_ok=True)
        if record['original']:
            staged = self.active.parent / ('.hypratomic-restore-' + transaction.name)
            copy_entry(source, staged)
        self.swap(staged, transaction, None)
        print(f'Restored the previous configuration. Outgoing configuration: {transaction}')
        print('Log out and log in; from a TTY, return to the login screen and start a new session.')

    def run(self, action, dry_run=False):
        self.check_paths()
        if dry_run:
            if action == 'activate':
                self.preflight()
            print(f'Would {action}: {self.active}\nOverrides: {self.user}\nRecovery state: {self.state}')
            print(f'Managed configuration format: {self.format}. No files written; parsing happens on activation.')
            return
        self.state.mkdir(parents=True, exist_ok=True, mode=0o700)
        with (self.state / 'lock').open('a') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            self.recover()
            getattr(self, action)()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=('bootstrap', 'activate', 'restore'))
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()
    if os.geteuid() == 0:
        parser.error('Run as your desktop user, without sudo')
    os.umask(0o077)
    home = Path.home()
    instance = Configuration(home, os.environ.get('XDG_CONFIG_HOME', home / '.config'),
                             os.environ.get('XDG_STATE_HOME', home / '.local/state'),
                             Path(__file__).resolve().parents[2])
    def interrupted(signum, _frame):
        raise InterruptedError(f'Interrupted by signal {signum}')
    signal.signal(signal.SIGTERM, interrupted)
    try:
        instance.run(args.action, args.dry_run)
    except (OSError, RuntimeError, ValueError, subprocess.CalledProcessError) as error:
        print(f'hypratomic-{args.action}: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
